#!/usr/bin/env bash
# This script is used to check the status of TCP and UDP ports on a server.

if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ping -c 5 "$1"
